[package]
name = "mandelbrick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kurbo = "0.9.0"
piet = "0.6.2"
piet-common = { version = "0.6.2", features = ["png"] }
piet-svg = "0.6.2"
